// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// VaultsColumns holds the columns for the "vaults" table.
	VaultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "reference_number", Type: field.TypeString, Unique: true, Size: 36},
	}
	// VaultsTable holds the schema information for the "vaults" table.
	VaultsTable = &schema.Table{
		Name:        "vaults",
		Columns:     VaultsColumns,
		PrimaryKey:  []*schema.Column{VaultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		VaultsTable,
	}
)

func init() {
}
