// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/pepeunlimited/checkout/internal/app/app1/ent/migrate"

	"github.com/pepeunlimited/checkout/internal/app/app1/ent/vault"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Vault is the client for interacting with the Vault builders.
	Vault *VaultClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	c := config{log: log.Println}
	c.options(opts...)
	return &Client{
		config: c,
		Schema: migrate.NewSchema(c.driver),
		Vault:  NewVaultClient(c),
	}
}

// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug}
	return &Tx{
		config: cfg,
		Vault:  NewVaultClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Vault.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true}
	return &Client{
		config: cfg,
		Schema: migrate.NewSchema(cfg.driver),
		Vault:  NewVaultClient(cfg),
	}
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// VaultClient is a client for the Vault schema.
type VaultClient struct {
	config
}

// NewVaultClient returns a client for the Vault from the given config.
func NewVaultClient(c config) *VaultClient {
	return &VaultClient{config: c}
}

// Create returns a create builder for Vault.
func (c *VaultClient) Create() *VaultCreate {
	return &VaultCreate{config: c.config}
}

// Update returns an update builder for Vault.
func (c *VaultClient) Update() *VaultUpdate {
	return &VaultUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *VaultClient) UpdateOne(v *Vault) *VaultUpdateOne {
	return c.UpdateOneID(v.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *VaultClient) UpdateOneID(id int) *VaultUpdateOne {
	return &VaultUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for Vault.
func (c *VaultClient) Delete() *VaultDelete {
	return &VaultDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *VaultClient) DeleteOne(v *Vault) *VaultDeleteOne {
	return c.DeleteOneID(v.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *VaultClient) DeleteOneID(id int) *VaultDeleteOne {
	return &VaultDeleteOne{c.Delete().Where(vault.ID(id))}
}

// Create returns a query builder for Vault.
func (c *VaultClient) Query() *VaultQuery {
	return &VaultQuery{config: c.config}
}

// Get returns a Vault entity by its id.
func (c *VaultClient) Get(ctx context.Context, id int) (*Vault, error) {
	return c.Query().Where(vault.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VaultClient) GetX(ctx context.Context, id int) *Vault {
	v, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return v
}
