// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Vault is the predicate function for vault builders.
type Vault func(*sql.Selector)
