kind: Deployment
apiVersion: apps/v1
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - env:
            - name: RPC_APPLE_IAP_HOST
              value: apple-iap
            - name: RPC_ACCOUNTS_HOST
              value: accounts
            - name: RPC_PAYMENT_HOST
              value: billing
            - name: RPC_ORDER_HOST
              value: billing
            - name: RPC_PRODUCT_HOST
              value: products
            - name: RPC_PRICE_HOST
              value: products
          image: pepeunlimited/checkout:0.1.4-5-gc9df32a
          name: checkout
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always