kind: Deployment
apiVersion: apps/v1
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - env:
            - name: RPC_ACCOUNTS_HOST
              value: accounts
            - name: MYSQL_DATABASE
              value: users
            - name: MYSQL_HOST
              value: external-mysql.default.svc
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: root
          image: pepeunlimited/checkout:0.1.4-1-ged118b6
          name: checkout
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always