// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkout.proto

package checkoutrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCheckoutParams struct {
	PaymentInstrumentId  uint32   `protobuf:"varint,1,opt,name=payment_instrument_id,json=paymentInstrumentId,proto3" json:"payment_instrument_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            int64    `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCheckoutParams) Reset()         { *m = CreateCheckoutParams{} }
func (m *CreateCheckoutParams) String() string { return proto.CompactTextString(m) }
func (*CreateCheckoutParams) ProtoMessage()    {}
func (*CreateCheckoutParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{0}
}

func (m *CreateCheckoutParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCheckoutParams.Unmarshal(m, b)
}
func (m *CreateCheckoutParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCheckoutParams.Marshal(b, m, deterministic)
}
func (m *CreateCheckoutParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCheckoutParams.Merge(m, src)
}
func (m *CreateCheckoutParams) XXX_Size() int {
	return xxx_messageInfo_CreateCheckoutParams.Size(m)
}
func (m *CreateCheckoutParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCheckoutParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCheckoutParams proto.InternalMessageInfo

func (m *CreateCheckoutParams) GetPaymentInstrumentId() uint32 {
	if m != nil {
		return m.PaymentInstrumentId
	}
	return 0
}

func (m *CreateCheckoutParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateCheckoutParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type Checkout struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId            int64    `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PaymentInstrumentId  uint32   `protobuf:"varint,3,opt,name=payment_instrument_id,json=paymentInstrumentId,proto3" json:"payment_instrument_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkout) Reset()         { *m = Checkout{} }
func (m *Checkout) String() string { return proto.CompactTextString(m) }
func (*Checkout) ProtoMessage()    {}
func (*Checkout) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{1}
}

func (m *Checkout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkout.Unmarshal(m, b)
}
func (m *Checkout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkout.Marshal(b, m, deterministic)
}
func (m *Checkout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkout.Merge(m, src)
}
func (m *Checkout) XXX_Size() int {
	return xxx_messageInfo_Checkout.Size(m)
}
func (m *Checkout) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkout.DiscardUnknown(m)
}

var xxx_messageInfo_Checkout proto.InternalMessageInfo

func (m *Checkout) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Checkout) GetPaymentId() int64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *Checkout) GetPaymentInstrumentId() uint32 {
	if m != nil {
		return m.PaymentInstrumentId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateCheckoutParams)(nil), "pepeunlimited.checkout.CreateCheckoutParams")
	proto.RegisterType((*Checkout)(nil), "pepeunlimited.checkout.Checkout")
}

func init() { proto.RegisterFile("checkout.proto", fileDescriptor_a95bdbc7e39fe4fd) }

var fileDescriptor_a95bdbc7e39fe4fd = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x85, 0x95, 0x9b, 0xab, 0xb6, 0x0c, 0x6a, 0x91, 0xcc, 0x5f, 0x09, 0x02, 0x45, 0x5d, 0x75,
	0x81, 0x52, 0xa9, 0xbc, 0x01, 0x5d, 0x65, 0x87, 0xca, 0x8e, 0x0d, 0xb8, 0xf6, 0x50, 0x22, 0x9a,
	0xd8, 0x1a, 0xdb, 0x40, 0xb7, 0x3c, 0x39, 0xaa, 0x63, 0x23, 0x81, 0x9a, 0xdd, 0xcc, 0x7c, 0xc7,
	0x67, 0x8e, 0xc6, 0x30, 0x12, 0xaf, 0x28, 0xde, 0x94, 0xb3, 0x85, 0x26, 0x65, 0x15, 0x3b, 0xd3,
	0xa8, 0xd1, 0x35, 0x9b, 0xaa, 0xae, 0x2c, 0xca, 0x22, 0xd2, 0xec, 0x72, 0xad, 0xd4, 0x7a, 0x83,
	0x33, 0xaf, 0x5a, 0xb9, 0x97, 0x19, 0xd6, 0xda, 0x6e, 0xdb, 0x47, 0xd9, 0xf5, 0x5f, 0xf8, 0x41,
	0x5c, 0x6b, 0x24, 0xd3, 0xf2, 0xc9, 0x57, 0x02, 0x27, 0x0b, 0x42, 0x6e, 0x71, 0x11, 0xfc, 0xee,
	0x39, 0xf1, 0xda, 0xb0, 0x39, 0x9c, 0x6a, 0xbe, 0xad, 0xb1, 0xb1, 0x4f, 0x55, 0x63, 0x2c, 0xb9,
	0xb6, 0x94, 0xe3, 0x24, 0x4f, 0xa6, 0xc3, 0xe5, 0x71, 0x80, 0xe5, 0x0f, 0x2b, 0x25, 0x3b, 0x87,
	0xbe, 0x33, 0x48, 0x3b, 0x55, 0x9a, 0x27, 0xd3, 0x74, 0xd9, 0xdb, 0xb5, 0xa5, 0x64, 0x57, 0x00,
	0x9a, 0x94, 0x74, 0xc2, 0x3b, 0xfc, 0xf7, 0xec, 0x20, 0x4c, 0x4a, 0x39, 0xf9, 0x84, 0x41, 0xdc,
	0xce, 0x2e, 0x60, 0xa0, 0x48, 0xb6, 0x26, 0x89, 0x17, 0xf6, 0x7d, 0x1f, 0x5c, 0x62, 0x24, 0x39,
	0xfe, 0x17, 0x5c, 0x42, 0x0e, 0xd9, 0x9d, 0x38, 0xed, 0x4c, 0x3c, 0x37, 0x70, 0x14, 0x37, 0x3f,
	0x20, 0xbd, 0x57, 0x02, 0xd9, 0x33, 0x8c, 0x7e, 0x1f, 0x84, 0xdd, 0x14, 0xfb, 0x2f, 0x5f, 0xec,
	0x3b, 0x5c, 0x96, 0x77, 0xaa, 0x43, 0x71, 0x37, 0x7c, 0x3c, 0x8c, 0x43, 0xd2, 0x62, 0xd5, 0xf3,
	0x3f, 0x71, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x7c, 0x77, 0x68, 0xf0, 0x01, 0x00, 0x00,
}
