// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkout.proto

package checkoutrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCheckoutParams struct {
	PaymentInstrumentId   *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=payment_instrument_id,json=paymentInstrumentId,proto3" json:"payment_instrument_id,omitempty"`
	PaymentInstrumentType *wrappers.StringValue `protobuf:"bytes,2,opt,name=payment_instrument_type,json=paymentInstrumentType,proto3" json:"payment_instrument_type,omitempty"`
	UserId                int64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId             int64                 `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}

func (m *CreateCheckoutParams) Reset()         { *m = CreateCheckoutParams{} }
func (m *CreateCheckoutParams) String() string { return proto.CompactTextString(m) }
func (*CreateCheckoutParams) ProtoMessage()    {}
func (*CreateCheckoutParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{0}
}

func (m *CreateCheckoutParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCheckoutParams.Unmarshal(m, b)
}
func (m *CreateCheckoutParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCheckoutParams.Marshal(b, m, deterministic)
}
func (m *CreateCheckoutParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCheckoutParams.Merge(m, src)
}
func (m *CreateCheckoutParams) XXX_Size() int {
	return xxx_messageInfo_CreateCheckoutParams.Size(m)
}
func (m *CreateCheckoutParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCheckoutParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCheckoutParams proto.InternalMessageInfo

func (m *CreateCheckoutParams) GetPaymentInstrumentId() *wrappers.UInt32Value {
	if m != nil {
		return m.PaymentInstrumentId
	}
	return nil
}

func (m *CreateCheckoutParams) GetPaymentInstrumentType() *wrappers.StringValue {
	if m != nil {
		return m.PaymentInstrumentType
	}
	return nil
}

func (m *CreateCheckoutParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateCheckoutParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type CreateSubscriptionParams struct {
	PaymentInstrumentId   *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=payment_instrument_id,json=paymentInstrumentId,proto3" json:"payment_instrument_id,omitempty"`
	PaymentInstrumentType *wrappers.StringValue `protobuf:"bytes,2,opt,name=payment_instrument_type,json=paymentInstrumentType,proto3" json:"payment_instrument_type,omitempty"`
	UserId                int64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId             int64                 `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UseTrial              bool                  `protobuf:"varint,5,opt,name=use_trial,json=useTrial,proto3" json:"use_trial,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}

func (m *CreateSubscriptionParams) Reset()         { *m = CreateSubscriptionParams{} }
func (m *CreateSubscriptionParams) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionParams) ProtoMessage()    {}
func (*CreateSubscriptionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{1}
}

func (m *CreateSubscriptionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionParams.Unmarshal(m, b)
}
func (m *CreateSubscriptionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionParams.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionParams.Merge(m, src)
}
func (m *CreateSubscriptionParams) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionParams.Size(m)
}
func (m *CreateSubscriptionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionParams proto.InternalMessageInfo

func (m *CreateSubscriptionParams) GetPaymentInstrumentId() *wrappers.UInt32Value {
	if m != nil {
		return m.PaymentInstrumentId
	}
	return nil
}

func (m *CreateSubscriptionParams) GetPaymentInstrumentType() *wrappers.StringValue {
	if m != nil {
		return m.PaymentInstrumentType
	}
	return nil
}

func (m *CreateSubscriptionParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateSubscriptionParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *CreateSubscriptionParams) GetUseTrial() bool {
	if m != nil {
		return m.UseTrial
	}
	return false
}

type Checkout struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkout) Reset()         { *m = Checkout{} }
func (m *Checkout) String() string { return proto.CompactTextString(m) }
func (*Checkout) ProtoMessage()    {}
func (*Checkout) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{2}
}

func (m *Checkout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkout.Unmarshal(m, b)
}
func (m *Checkout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkout.Marshal(b, m, deterministic)
}
func (m *Checkout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkout.Merge(m, src)
}
func (m *Checkout) XXX_Size() int {
	return xxx_messageInfo_Checkout.Size(m)
}
func (m *Checkout) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkout.DiscardUnknown(m)
}

var xxx_messageInfo_Checkout proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateCheckoutParams)(nil), "pepeunlimited.checkout.CreateCheckoutParams")
	proto.RegisterType((*CreateSubscriptionParams)(nil), "pepeunlimited.checkout.CreateSubscriptionParams")
	proto.RegisterType((*Checkout)(nil), "pepeunlimited.checkout.Checkout")
}

func init() { proto.RegisterFile("checkout.proto", fileDescriptor_a95bdbc7e39fe4fd) }

var fileDescriptor_a95bdbc7e39fe4fd = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x53, 0x50, 0x84, 0x21, 0x62, 0xb2, 0x8a, 0x34, 0xa0, 0xa6, 0xe1, 0xc4, 0xc1, 0x2c,
	0x06, 0xde, 0x40, 0x4e, 0xbd, 0x11, 0x40, 0x0f, 0x5e, 0x70, 0x69, 0x47, 0xd8, 0xd8, 0x76, 0x37,
	0xfb, 0x47, 0xd3, 0x27, 0xf1, 0xe9, 0x7c, 0x0d, 0xcf, 0x86, 0x96, 0x9a, 0x28, 0xa0, 0x0f, 0xe0,
	0xad, 0xb3, 0xdf, 0xcc, 0x6f, 0x66, 0x3a, 0x1f, 0x34, 0x82, 0x15, 0x06, 0xcf, 0xc2, 0x1a, 0x2a,
	0x95, 0x30, 0x82, 0x9c, 0x4b, 0x94, 0x68, 0x93, 0x88, 0xc7, 0xdc, 0x60, 0x48, 0x0b, 0xb5, 0xdd,
	0x59, 0x0a, 0xb1, 0x8c, 0xb0, 0x9f, 0x65, 0x2d, 0xec, 0x53, 0x1f, 0x63, 0x69, 0xd2, 0xbc, 0xa8,
	0x7d, 0xf5, 0x53, 0x7c, 0x55, 0x4c, 0x4a, 0x54, 0x3a, 0xd7, 0xbb, 0x1f, 0x0e, 0x9c, 0x8d, 0x14,
	0x32, 0x83, 0xa3, 0x0d, 0x6f, 0xcc, 0x14, 0x8b, 0x35, 0x19, 0x43, 0x53, 0xb2, 0x34, 0xc6, 0xc4,
	0xcc, 0x79, 0xa2, 0x8d, 0xb2, 0xf9, 0x67, 0xe8, 0x3a, 0x9e, 0xd3, 0xab, 0x0f, 0x2e, 0x68, 0x0e,
	0xa6, 0x05, 0x98, 0xde, 0xf9, 0x89, 0x19, 0x0e, 0xee, 0x59, 0x64, 0x71, 0x72, 0xba, 0x29, 0xf5,
	0xbf, 0x2a, 0xfd, 0x90, 0xcc, 0xa0, 0xb5, 0x83, 0x68, 0x52, 0x89, 0x6e, 0x69, 0x0f, 0x73, 0x6a,
	0x14, 0x4f, 0x96, 0x39, 0xb3, 0xb9, 0xc5, 0x9c, 0xa5, 0x12, 0x49, 0x0b, 0x8e, 0xac, 0x46, 0xb5,
	0x9e, 0xac, 0xec, 0x39, 0xbd, 0xf2, 0xa4, 0xb2, 0x0e, 0xfd, 0x90, 0x5c, 0x02, 0x48, 0x25, 0x42,
	0x1b, 0x64, 0x53, 0x1f, 0x64, 0x5a, 0x6d, 0xf3, 0xe2, 0x87, 0xdd, 0xb7, 0x12, 0xb8, 0xf9, 0xe2,
	0x53, 0xbb, 0xd0, 0x81, 0xe2, 0xd2, 0x70, 0x91, 0xfc, 0x8f, 0xe5, 0x49, 0x07, 0x6a, 0x56, 0xe3,
	0xdc, 0x28, 0xce, 0x22, 0xf7, 0xd0, 0x73, 0x7a, 0xd5, 0x49, 0xd5, 0x6a, 0x9c, 0xad, 0xe3, 0x2e,
	0x40, 0xb5, 0xf0, 0xc2, 0xe0, 0xdd, 0x81, 0x93, 0x22, 0x98, 0xa2, 0x7a, 0xe1, 0x01, 0x92, 0x47,
	0x68, 0x7c, 0x77, 0x0c, 0xb9, 0xa6, 0xbb, 0xad, 0x49, 0x77, 0x39, 0xab, 0xed, 0xed, 0xcd, 0x2e,
	0x78, 0x2b, 0x20, 0xdb, 0xa7, 0x21, 0x37, 0xbf, 0x77, 0xd9, 0x3e, 0xe3, 0xdf, 0x9d, 0x6e, 0x8f,
	0x1f, 0xea, 0xc5, 0xa3, 0x92, 0xc1, 0xa2, 0x92, 0xfd, 0xfc, 0xe1, 0x67, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x5d, 0xc0, 0x6f, 0xcc, 0x7b, 0x03, 0x00, 0x00,
}
