// Code generated by entc, DO NOT EDIT.

package vault

import (
	"github.com/pepeunlimited/checkout/internal/app/app1/ent/schema"
)

const (
	// Label holds the string label denoting the vault type in the database.
	Label = "vault"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount vertex property in the database.
	FieldAmount = "amount"
	// FieldReferenceNumber holds the string denoting the reference_number vertex property in the database.
	FieldReferenceNumber = "reference_number"

	// Table holds the table name of the vault in the database.
	Table = "vaults"
)

// Columns holds all SQL columns for vault fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldReferenceNumber,
}

var (
	fields = schema.Vault{}.Fields()

	// descReferenceNumber is the schema descriptor for reference_number field.
	descReferenceNumber = fields[1].Descriptor()
	// ReferenceNumberValidator is a validator for the "reference_number" field. It is called by the builders before save.
	ReferenceNumberValidator = descReferenceNumber.Validators[0].(func(string) error)
)
